export type Country = { code: string; name: string; flag: string };

// ISO 3166-1 alpha-2; flag is regional indicator emoji
export const COUNTRIES: Country[] = [
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "UG", name: "Uganda", flag: "🇺🇬" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "SN", name: "Senegal", flag: "🇸🇳" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "MA", name: "Morocco", flag: "🇲🇦" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
  { code: "BW", name: "Botswana", flag: "🇧🇼" },
  { code: "NA", name: "Namibia", flag: "🇳🇦" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "MW", name: "Malawi", flag: "🇲🇼" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BJ", name: "Benin", flag: "🇧🇯" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "GM", name: "Gambia", flag: "🇬🇲" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "LR", name: "Liberia", flag: "🇱🇷" },
  { code: "GN", name: "Guinea", flag: "🇬🇳" },
  { code: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "TD", name: "Chad", flag: "🇹🇩" },
  { code: "SD", name: "Sudan", flag: "🇸🇩" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸" },
  { code: "SO", name: "Somalia", flag: "🇸🇴" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷" },
  { code: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "CG", name: "Congo", flag: "🇨🇬" },
  { code: "CD", name: "DR Congo", flag: "🇨🇩" },
  { code: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨" },
  { code: "CV", name: "Cape Verde", flag: "🇨🇻" },
  { code: "ST", name: "São Tomé & Príncipe", flag: "🇸🇹" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷" },
  { code: "LY", name: "Libya", flag: "🇱🇾" },
  { code: "KM", name: "Comoros", flag: "🇰🇲" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫" },
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "CZ", name: "Czechia", flag: "🇨🇿" },
  { code: "GR", name: "Greece", flag: "🇬🇷" },
  { code: "RO", name: "Romania", flag: "🇷🇴" },
  { code: "HU", name: "Hungary", flag: "🇭🇺" },
  { code: "TR", name: "Türkiye", flag: "🇹🇷" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "JO", name: "Jordan", flag: "🇯🇴" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "KR", name: "South Korea", flag: "🇰🇷" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲" },
  { code: "TT", name: "Trinidad & Tobago", flag: "🇹🇹" },
];

export const DIAL_CODES: Record<string, string> = {
  NG: "234", GH: "233", KE: "254", ZA: "27", UG: "256", TZ: "255", RW: "250",
  SN: "221", CI: "225", CM: "237", EG: "20", MA: "212", ET: "251", DZ: "213",
  TN: "216", AO: "244", ZM: "260", ZW: "263", BW: "267", NA: "264", MZ: "258",
  MW: "265", MG: "261", ML: "223", BF: "226", BJ: "229", TG: "228", GM: "220",
  SL: "232", LR: "231", GN: "224", NE: "227", TD: "235", SD: "249", SS: "211",
  SO: "252", DJ: "253", ER: "291", GA: "241", CG: "242", CD: "243", BI: "257",
  LS: "266", SZ: "268", MU: "230", SC: "248", CV: "238", ST: "239", GQ: "240",
  GW: "245", MR: "222", LY: "218", KM: "269", CF: "236",
  US: "1", GB: "44", CA: "1", DE: "49", FR: "33", IT: "39", ES: "34", PT: "351",
  NL: "31", BE: "32", CH: "41", AT: "43", SE: "46", NO: "47", DK: "45", FI: "358",
  IE: "353", PL: "48", CZ: "420", GR: "30", RO: "40", HU: "36", TR: "90", RU: "7",
  UA: "380", AE: "971", SA: "966", QA: "974", KW: "965", BH: "973", OM: "968",
  JO: "962", LB: "961", IL: "972", IR: "98", IQ: "964", PK: "92", IN: "91",
  BD: "880", LK: "94", NP: "977", CN: "86", JP: "81", KR: "82", SG: "65", MY: "60",
  ID: "62", PH: "63", TH: "66", VN: "84", AU: "61", NZ: "64", BR: "55", AR: "54",
  CL: "56", CO: "57", PE: "51", MX: "52", VE: "58", EC: "593", UY: "598", PY: "595",
  BO: "591", CR: "506", PA: "507", DO: "1", JM: "1", TT: "1",
};

export type IdType = "NIN" | "BVN" | "PASSPORT";

export function idTypesForCountry(code: string): IdType[] {
  if (code === "NG") return ["NIN", "BVN"];
  return ["PASSPORT"];
}

export const ID_LABELS: Record<IdType, { title: string; desc: string }> = {
  NIN: { title: "National ID (NIN)", desc: "11-digit National Identification Number" },
  BVN: { title: "Bank Verification (BVN)", desc: "11-digit BVN tied to your bank" },
  PASSPORT: { title: "International Passport", desc: "Photo page of your passport" },
};
