/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionIdRouteImport } from './routes/transaction.$id'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPayRouteImport } from './routes/_app.pay'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppPayIndexRouteImport } from './routes/_app.pay.index'
import { Route as AppNumbersIndexRouteImport } from './routes/_app.numbers.index'
import { Route as AppEsimsIndexRouteImport } from './routes/_app.esims.index'
import { Route as AppCardsIndexRouteImport } from './routes/_app.cards.index'
import { Route as AppProfileReferralsRouteImport } from './routes/_app.profile_.referrals'
import { Route as AppProfileLegalRouteImport } from './routes/_app.profile_.legal'
import { Route as AppProfileHelpRouteImport } from './routes/_app.profile_.help'
import { Route as AppPayTvRouteImport } from './routes/_app.pay.tv'
import { Route as AppPayInternetRouteImport } from './routes/_app.pay.internet'
import { Route as AppPayEsimRouteImport } from './routes/_app.pay.esim'
import { Route as AppPayElectricityRouteImport } from './routes/_app.pay.electricity'
import { Route as AppPayDataRouteImport } from './routes/_app.pay.data'
import { Route as AppPayBettingRouteImport } from './routes/_app.pay.betting'
import { Route as AppPayAirtimeRouteImport } from './routes/_app.pay.airtime'
import { Route as AppPayServiceRouteImport } from './routes/_app.pay.$service'
import { Route as AppNumbersIdRouteImport } from './routes/_app.numbers.$id'
import { Route as AppEsimsIdRouteImport } from './routes/_app.esims.$id'
import { Route as AppCardsNewRouteImport } from './routes/_app.cards.new'
import { Route as AppCardsIdRouteImport } from './routes/_app.cards.$id'
import { Route as AppProfileSecurityTwofaRouteImport } from './routes/_app.profile_.security.twofa'
import { Route as AppProfileSecurityPinRouteImport } from './routes/_app.profile_.security.pin'
import { Route as AppCardsIdTxnTxnIdRouteImport } from './routes/_app.cards.$id_.txn.$txnId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIdRoute = TransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPayRoute = AppPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppPayIndexRoute = AppPayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPayRoute,
} as any)
const AppNumbersIndexRoute = AppNumbersIndexRouteImport.update({
  id: '/numbers/',
  path: '/numbers/',
  getParentRoute: () => AppRoute,
} as any)
const AppEsimsIndexRoute = AppEsimsIndexRouteImport.update({
  id: '/esims/',
  path: '/esims/',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsIndexRoute = AppCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileReferralsRoute = AppProfileReferralsRouteImport.update({
  id: '/profile_/referrals',
  path: '/profile/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileLegalRoute = AppProfileLegalRouteImport.update({
  id: '/profile_/legal',
  path: '/profile/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileHelpRoute = AppProfileHelpRouteImport.update({
  id: '/profile_/help',
  path: '/profile/help',
  getParentRoute: () => AppRoute,
} as any)
const AppPayTvRoute = AppPayTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayInternetRoute = AppPayInternetRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayEsimRoute = AppPayEsimRouteImport.update({
  id: '/esim',
  path: '/esim',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayElectricityRoute = AppPayElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayDataRoute = AppPayDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayBettingRoute = AppPayBettingRouteImport.update({
  id: '/betting',
  path: '/betting',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayAirtimeRoute = AppPayAirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => AppPayRoute,
} as any)
const AppPayServiceRoute = AppPayServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => AppPayRoute,
} as any)
const AppNumbersIdRoute = AppNumbersIdRouteImport.update({
  id: '/numbers/$id',
  path: '/numbers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEsimsIdRoute = AppEsimsIdRouteImport.update({
  id: '/esims/$id',
  path: '/esims/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsNewRoute = AppCardsNewRouteImport.update({
  id: '/cards/new',
  path: '/cards/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsIdRoute = AppCardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSecurityTwofaRoute = AppProfileSecurityTwofaRouteImport.update({
  id: '/profile_/security/twofa',
  path: '/profile/security/twofa',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSecurityPinRoute = AppProfileSecurityPinRouteImport.update({
  id: '/profile_/security/pin',
  path: '/profile/security/pin',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsIdTxnTxnIdRoute = AppCardsIdTxnTxnIdRouteImport.update({
  id: '/cards/$id_/txn/$txnId',
  path: '/cards/$id/txn/$txnId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kyc': typeof KycRoute
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AppHomeRoute
  '/pay': typeof AppPayRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/cards/$id': typeof AppCardsIdRoute
  '/cards/new': typeof AppCardsNewRoute
  '/esims/$id': typeof AppEsimsIdRoute
  '/numbers/$id': typeof AppNumbersIdRoute
  '/pay/$service': typeof AppPayServiceRoute
  '/pay/airtime': typeof AppPayAirtimeRoute
  '/pay/betting': typeof AppPayBettingRoute
  '/pay/data': typeof AppPayDataRoute
  '/pay/electricity': typeof AppPayElectricityRoute
  '/pay/esim': typeof AppPayEsimRoute
  '/pay/internet': typeof AppPayInternetRoute
  '/pay/tv': typeof AppPayTvRoute
  '/profile/help': typeof AppProfileHelpRoute
  '/profile/legal': typeof AppProfileLegalRoute
  '/profile/referrals': typeof AppProfileReferralsRoute
  '/cards/': typeof AppCardsIndexRoute
  '/esims/': typeof AppEsimsIndexRoute
  '/numbers/': typeof AppNumbersIndexRoute
  '/pay/': typeof AppPayIndexRoute
  '/profile/security/pin': typeof AppProfileSecurityPinRoute
  '/profile/security/twofa': typeof AppProfileSecurityTwofaRoute
  '/cards/$id/txn/$txnId': typeof AppCardsIdTxnTxnIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kyc': typeof KycRoute
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/cards/$id': typeof AppCardsIdRoute
  '/cards/new': typeof AppCardsNewRoute
  '/esims/$id': typeof AppEsimsIdRoute
  '/numbers/$id': typeof AppNumbersIdRoute
  '/pay/$service': typeof AppPayServiceRoute
  '/pay/airtime': typeof AppPayAirtimeRoute
  '/pay/betting': typeof AppPayBettingRoute
  '/pay/data': typeof AppPayDataRoute
  '/pay/electricity': typeof AppPayElectricityRoute
  '/pay/esim': typeof AppPayEsimRoute
  '/pay/internet': typeof AppPayInternetRoute
  '/pay/tv': typeof AppPayTvRoute
  '/profile/help': typeof AppProfileHelpRoute
  '/profile/legal': typeof AppProfileLegalRoute
  '/profile/referrals': typeof AppProfileReferralsRoute
  '/cards': typeof AppCardsIndexRoute
  '/esims': typeof AppEsimsIndexRoute
  '/numbers': typeof AppNumbersIndexRoute
  '/pay': typeof AppPayIndexRoute
  '/profile/security/pin': typeof AppProfileSecurityPinRoute
  '/profile/security/twofa': typeof AppProfileSecurityTwofaRoute
  '/cards/$id/txn/$txnId': typeof AppCardsIdTxnTxnIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/kyc': typeof KycRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/pay': typeof AppPayRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/_app/cards/$id': typeof AppCardsIdRoute
  '/_app/cards/new': typeof AppCardsNewRoute
  '/_app/esims/$id': typeof AppEsimsIdRoute
  '/_app/numbers/$id': typeof AppNumbersIdRoute
  '/_app/pay/$service': typeof AppPayServiceRoute
  '/_app/pay/airtime': typeof AppPayAirtimeRoute
  '/_app/pay/betting': typeof AppPayBettingRoute
  '/_app/pay/data': typeof AppPayDataRoute
  '/_app/pay/electricity': typeof AppPayElectricityRoute
  '/_app/pay/esim': typeof AppPayEsimRoute
  '/_app/pay/internet': typeof AppPayInternetRoute
  '/_app/pay/tv': typeof AppPayTvRoute
  '/_app/profile_/help': typeof AppProfileHelpRoute
  '/_app/profile_/legal': typeof AppProfileLegalRoute
  '/_app/profile_/referrals': typeof AppProfileReferralsRoute
  '/_app/cards/': typeof AppCardsIndexRoute
  '/_app/esims/': typeof AppEsimsIndexRoute
  '/_app/numbers/': typeof AppNumbersIndexRoute
  '/_app/pay/': typeof AppPayIndexRoute
  '/_app/profile_/security/pin': typeof AppProfileSecurityPinRoute
  '/_app/profile_/security/twofa': typeof AppProfileSecurityTwofaRoute
  '/_app/cards/$id_/txn/$txnId': typeof AppCardsIdTxnTxnIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kyc'
    | '/onboarding'
    | '/home'
    | '/pay'
    | '/profile'
    | '/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/transaction/$id'
    | '/cards/$id'
    | '/cards/new'
    | '/esims/$id'
    | '/numbers/$id'
    | '/pay/$service'
    | '/pay/airtime'
    | '/pay/betting'
    | '/pay/data'
    | '/pay/electricity'
    | '/pay/esim'
    | '/pay/internet'
    | '/pay/tv'
    | '/profile/help'
    | '/profile/legal'
    | '/profile/referrals'
    | '/cards/'
    | '/esims/'
    | '/numbers/'
    | '/pay/'
    | '/profile/security/pin'
    | '/profile/security/twofa'
    | '/cards/$id/txn/$txnId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kyc'
    | '/onboarding'
    | '/home'
    | '/profile'
    | '/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/transaction/$id'
    | '/cards/$id'
    | '/cards/new'
    | '/esims/$id'
    | '/numbers/$id'
    | '/pay/$service'
    | '/pay/airtime'
    | '/pay/betting'
    | '/pay/data'
    | '/pay/electricity'
    | '/pay/esim'
    | '/pay/internet'
    | '/pay/tv'
    | '/profile/help'
    | '/profile/legal'
    | '/profile/referrals'
    | '/cards'
    | '/esims'
    | '/numbers'
    | '/pay'
    | '/profile/security/pin'
    | '/profile/security/twofa'
    | '/cards/$id/txn/$txnId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/kyc'
    | '/onboarding'
    | '/_app/home'
    | '/_app/pay'
    | '/_app/profile'
    | '/_app/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/transaction/$id'
    | '/_app/cards/$id'
    | '/_app/cards/new'
    | '/_app/esims/$id'
    | '/_app/numbers/$id'
    | '/_app/pay/$service'
    | '/_app/pay/airtime'
    | '/_app/pay/betting'
    | '/_app/pay/data'
    | '/_app/pay/electricity'
    | '/_app/pay/esim'
    | '/_app/pay/internet'
    | '/_app/pay/tv'
    | '/_app/profile_/help'
    | '/_app/profile_/legal'
    | '/_app/profile_/referrals'
    | '/_app/cards/'
    | '/_app/esims/'
    | '/_app/numbers/'
    | '/_app/pay/'
    | '/_app/profile_/security/pin'
    | '/_app/profile_/security/twofa'
    | '/_app/cards/$id_/txn/$txnId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  KycRoute: typeof KycRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  TransactionIdRoute: typeof TransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$id': {
      id: '/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof TransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay': {
      id: '/_app/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof AppPayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay/': {
      id: '/_app/pay/'
      path: '/'
      fullPath: '/pay/'
      preLoaderRoute: typeof AppPayIndexRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/numbers/': {
      id: '/_app/numbers/'
      path: '/numbers'
      fullPath: '/numbers/'
      preLoaderRoute: typeof AppNumbersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/esims/': {
      id: '/_app/esims/'
      path: '/esims'
      fullPath: '/esims/'
      preLoaderRoute: typeof AppEsimsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards/': {
      id: '/_app/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof AppCardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/referrals': {
      id: '/_app/profile_/referrals'
      path: '/profile/referrals'
      fullPath: '/profile/referrals'
      preLoaderRoute: typeof AppProfileReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/legal': {
      id: '/_app/profile_/legal'
      path: '/profile/legal'
      fullPath: '/profile/legal'
      preLoaderRoute: typeof AppProfileLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/help': {
      id: '/_app/profile_/help'
      path: '/profile/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof AppProfileHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay/tv': {
      id: '/_app/pay/tv'
      path: '/tv'
      fullPath: '/pay/tv'
      preLoaderRoute: typeof AppPayTvRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/internet': {
      id: '/_app/pay/internet'
      path: '/internet'
      fullPath: '/pay/internet'
      preLoaderRoute: typeof AppPayInternetRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/esim': {
      id: '/_app/pay/esim'
      path: '/esim'
      fullPath: '/pay/esim'
      preLoaderRoute: typeof AppPayEsimRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/electricity': {
      id: '/_app/pay/electricity'
      path: '/electricity'
      fullPath: '/pay/electricity'
      preLoaderRoute: typeof AppPayElectricityRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/data': {
      id: '/_app/pay/data'
      path: '/data'
      fullPath: '/pay/data'
      preLoaderRoute: typeof AppPayDataRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/betting': {
      id: '/_app/pay/betting'
      path: '/betting'
      fullPath: '/pay/betting'
      preLoaderRoute: typeof AppPayBettingRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/airtime': {
      id: '/_app/pay/airtime'
      path: '/airtime'
      fullPath: '/pay/airtime'
      preLoaderRoute: typeof AppPayAirtimeRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/pay/$service': {
      id: '/_app/pay/$service'
      path: '/$service'
      fullPath: '/pay/$service'
      preLoaderRoute: typeof AppPayServiceRouteImport
      parentRoute: typeof AppPayRoute
    }
    '/_app/numbers/$id': {
      id: '/_app/numbers/$id'
      path: '/numbers/$id'
      fullPath: '/numbers/$id'
      preLoaderRoute: typeof AppNumbersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/esims/$id': {
      id: '/_app/esims/$id'
      path: '/esims/$id'
      fullPath: '/esims/$id'
      preLoaderRoute: typeof AppEsimsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards/new': {
      id: '/_app/cards/new'
      path: '/cards/new'
      fullPath: '/cards/new'
      preLoaderRoute: typeof AppCardsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards/$id': {
      id: '/_app/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof AppCardsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/security/twofa': {
      id: '/_app/profile_/security/twofa'
      path: '/profile/security/twofa'
      fullPath: '/profile/security/twofa'
      preLoaderRoute: typeof AppProfileSecurityTwofaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/security/pin': {
      id: '/_app/profile_/security/pin'
      path: '/profile/security/pin'
      fullPath: '/profile/security/pin'
      preLoaderRoute: typeof AppProfileSecurityPinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards/$id_/txn/$txnId': {
      id: '/_app/cards/$id_/txn/$txnId'
      path: '/cards/$id/txn/$txnId'
      fullPath: '/cards/$id/txn/$txnId'
      preLoaderRoute: typeof AppCardsIdTxnTxnIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPayRouteChildren {
  AppPayServiceRoute: typeof AppPayServiceRoute
  AppPayAirtimeRoute: typeof AppPayAirtimeRoute
  AppPayBettingRoute: typeof AppPayBettingRoute
  AppPayDataRoute: typeof AppPayDataRoute
  AppPayElectricityRoute: typeof AppPayElectricityRoute
  AppPayEsimRoute: typeof AppPayEsimRoute
  AppPayInternetRoute: typeof AppPayInternetRoute
  AppPayTvRoute: typeof AppPayTvRoute
  AppPayIndexRoute: typeof AppPayIndexRoute
}

const AppPayRouteChildren: AppPayRouteChildren = {
  AppPayServiceRoute: AppPayServiceRoute,
  AppPayAirtimeRoute: AppPayAirtimeRoute,
  AppPayBettingRoute: AppPayBettingRoute,
  AppPayDataRoute: AppPayDataRoute,
  AppPayElectricityRoute: AppPayElectricityRoute,
  AppPayEsimRoute: AppPayEsimRoute,
  AppPayInternetRoute: AppPayInternetRoute,
  AppPayTvRoute: AppPayTvRoute,
  AppPayIndexRoute: AppPayIndexRoute,
}

const AppPayRouteWithChildren =
  AppPayRoute._addFileChildren(AppPayRouteChildren)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppPayRoute: typeof AppPayRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppWalletRoute: typeof AppWalletRoute
  AppCardsIdRoute: typeof AppCardsIdRoute
  AppCardsNewRoute: typeof AppCardsNewRoute
  AppEsimsIdRoute: typeof AppEsimsIdRoute
  AppNumbersIdRoute: typeof AppNumbersIdRoute
  AppProfileHelpRoute: typeof AppProfileHelpRoute
  AppProfileLegalRoute: typeof AppProfileLegalRoute
  AppProfileReferralsRoute: typeof AppProfileReferralsRoute
  AppCardsIndexRoute: typeof AppCardsIndexRoute
  AppEsimsIndexRoute: typeof AppEsimsIndexRoute
  AppNumbersIndexRoute: typeof AppNumbersIndexRoute
  AppProfileSecurityPinRoute: typeof AppProfileSecurityPinRoute
  AppProfileSecurityTwofaRoute: typeof AppProfileSecurityTwofaRoute
  AppCardsIdTxnTxnIdRoute: typeof AppCardsIdTxnTxnIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppPayRoute: AppPayRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppWalletRoute: AppWalletRoute,
  AppCardsIdRoute: AppCardsIdRoute,
  AppCardsNewRoute: AppCardsNewRoute,
  AppEsimsIdRoute: AppEsimsIdRoute,
  AppNumbersIdRoute: AppNumbersIdRoute,
  AppProfileHelpRoute: AppProfileHelpRoute,
  AppProfileLegalRoute: AppProfileLegalRoute,
  AppProfileReferralsRoute: AppProfileReferralsRoute,
  AppCardsIndexRoute: AppCardsIndexRoute,
  AppEsimsIndexRoute: AppEsimsIndexRoute,
  AppNumbersIndexRoute: AppNumbersIndexRoute,
  AppProfileSecurityPinRoute: AppProfileSecurityPinRoute,
  AppProfileSecurityTwofaRoute: AppProfileSecurityTwofaRoute,
  AppCardsIdTxnTxnIdRoute: AppCardsIdTxnTxnIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  KycRoute: KycRoute,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  TransactionIdRoute: TransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
