/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWalletsRouteImport } from './routes/_admin.wallets'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminCardsRouteImport } from './routes/_admin.cards'
import { Route as AdminWalletsIndexRouteImport } from './routes/_admin.wallets.index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin.users.index'
import { Route as AdminTransactionsIndexRouteImport } from './routes/_admin.transactions.index'
import { Route as AdminKycIndexRouteImport } from './routes/_admin.kyc.index'
import { Route as AdminCardsIndexRouteImport } from './routes/_admin.cards.index'
import { Route as AdminWalletsUsersRouteImport } from './routes/_admin.wallets.users'
import { Route as AdminWalletsTopupsRouteImport } from './routes/_admin.wallets.topups'
import { Route as AdminWalletsPayoutsRouteImport } from './routes/_admin.wallets.payouts'
import { Route as AdminWalletsFxRouteImport } from './routes/_admin.wallets.fx'
import { Route as AdminUsersIdRouteImport } from './routes/_admin.users.$id'
import { Route as AdminTransactionsIdRouteImport } from './routes/_admin.transactions.$id'
import { Route as AdminKycIdRouteImport } from './routes/_admin.kyc.$id'
import { Route as AdminCardsProgramsRouteImport } from './routes/_admin.cards.programs'
import { Route as AdminCardsIssuedRouteImport } from './routes/_admin.cards.issued'
import { Route as AdminCardsIdRouteImport } from './routes/_admin.cards.$id'
import { Route as AdminUsersIdIndexRouteImport } from './routes/_admin.users.$id.index'
import { Route as AdminUsersIdWalletsRouteImport } from './routes/_admin.users.$id.wallets'
import { Route as AdminUsersIdTransactionsRouteImport } from './routes/_admin.users.$id.transactions'
import { Route as AdminUsersIdNumbersRouteImport } from './routes/_admin.users.$id.numbers'
import { Route as AdminUsersIdNotesRouteImport } from './routes/_admin.users.$id.notes'
import { Route as AdminUsersIdKycRouteImport } from './routes/_admin.users.$id.kyc'
import { Route as AdminUsersIdEsimsRouteImport } from './routes/_admin.users.$id.esims'
import { Route as AdminUsersIdDevicesRouteImport } from './routes/_admin.users.$id.devices'
import { Route as AdminUsersIdCardsRouteImport } from './routes/_admin.users.$id.cards'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsIndexRoute = AdminWalletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycIndexRoute = AdminKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsIndexRoute = AdminCardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCardsRoute,
} as any)
const AdminWalletsUsersRoute = AdminWalletsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminWalletsTopupsRoute = AdminWalletsTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminWalletsPayoutsRoute = AdminWalletsPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminWalletsFxRoute = AdminWalletsFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsIdRoute = AdminTransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycIdRoute = AdminKycIdRouteImport.update({
  id: '/kyc/$id',
  path: '/kyc/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsProgramsRoute = AdminCardsProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminCardsRoute,
} as any)
const AdminCardsIssuedRoute = AdminCardsIssuedRouteImport.update({
  id: '/issued',
  path: '/issued',
  getParentRoute: () => AdminCardsRoute,
} as any)
const AdminCardsIdRoute = AdminCardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCardsRoute,
} as any)
const AdminUsersIdIndexRoute = AdminUsersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdWalletsRoute = AdminUsersIdWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdTransactionsRoute =
  AdminUsersIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminUsersIdRoute,
  } as any)
const AdminUsersIdNumbersRoute = AdminUsersIdNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdNotesRoute = AdminUsersIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdKycRoute = AdminUsersIdKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdEsimsRoute = AdminUsersIdEsimsRouteImport.update({
  id: '/esims',
  path: '/esims',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdDevicesRoute = AdminUsersIdDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminUsersIdRoute,
} as any)
const AdminUsersIdCardsRoute = AdminUsersIdCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminUsersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cards': typeof AdminCardsRouteWithChildren
  '/dashboard': typeof AdminDashboardRoute
  '/wallets': typeof AdminWalletsRouteWithChildren
  '/cards/$id': typeof AdminCardsIdRoute
  '/cards/issued': typeof AdminCardsIssuedRoute
  '/cards/programs': typeof AdminCardsProgramsRoute
  '/kyc/$id': typeof AdminKycIdRoute
  '/transactions/$id': typeof AdminTransactionsIdRoute
  '/users/$id': typeof AdminUsersIdRouteWithChildren
  '/wallets/fx': typeof AdminWalletsFxRoute
  '/wallets/payouts': typeof AdminWalletsPayoutsRoute
  '/wallets/topups': typeof AdminWalletsTopupsRoute
  '/wallets/users': typeof AdminWalletsUsersRoute
  '/cards/': typeof AdminCardsIndexRoute
  '/kyc/': typeof AdminKycIndexRoute
  '/transactions/': typeof AdminTransactionsIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/wallets/': typeof AdminWalletsIndexRoute
  '/users/$id/cards': typeof AdminUsersIdCardsRoute
  '/users/$id/devices': typeof AdminUsersIdDevicesRoute
  '/users/$id/esims': typeof AdminUsersIdEsimsRoute
  '/users/$id/kyc': typeof AdminUsersIdKycRoute
  '/users/$id/notes': typeof AdminUsersIdNotesRoute
  '/users/$id/numbers': typeof AdminUsersIdNumbersRoute
  '/users/$id/transactions': typeof AdminUsersIdTransactionsRoute
  '/users/$id/wallets': typeof AdminUsersIdWalletsRoute
  '/users/$id/': typeof AdminUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/cards/$id': typeof AdminCardsIdRoute
  '/cards/issued': typeof AdminCardsIssuedRoute
  '/cards/programs': typeof AdminCardsProgramsRoute
  '/kyc/$id': typeof AdminKycIdRoute
  '/transactions/$id': typeof AdminTransactionsIdRoute
  '/wallets/fx': typeof AdminWalletsFxRoute
  '/wallets/payouts': typeof AdminWalletsPayoutsRoute
  '/wallets/topups': typeof AdminWalletsTopupsRoute
  '/wallets/users': typeof AdminWalletsUsersRoute
  '/cards': typeof AdminCardsIndexRoute
  '/kyc': typeof AdminKycIndexRoute
  '/transactions': typeof AdminTransactionsIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/wallets': typeof AdminWalletsIndexRoute
  '/users/$id/cards': typeof AdminUsersIdCardsRoute
  '/users/$id/devices': typeof AdminUsersIdDevicesRoute
  '/users/$id/esims': typeof AdminUsersIdEsimsRoute
  '/users/$id/kyc': typeof AdminUsersIdKycRoute
  '/users/$id/notes': typeof AdminUsersIdNotesRoute
  '/users/$id/numbers': typeof AdminUsersIdNumbersRoute
  '/users/$id/transactions': typeof AdminUsersIdTransactionsRoute
  '/users/$id/wallets': typeof AdminUsersIdWalletsRoute
  '/users/$id': typeof AdminUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/cards': typeof AdminCardsRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/wallets': typeof AdminWalletsRouteWithChildren
  '/_admin/cards/$id': typeof AdminCardsIdRoute
  '/_admin/cards/issued': typeof AdminCardsIssuedRoute
  '/_admin/cards/programs': typeof AdminCardsProgramsRoute
  '/_admin/kyc/$id': typeof AdminKycIdRoute
  '/_admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/_admin/users/$id': typeof AdminUsersIdRouteWithChildren
  '/_admin/wallets/fx': typeof AdminWalletsFxRoute
  '/_admin/wallets/payouts': typeof AdminWalletsPayoutsRoute
  '/_admin/wallets/topups': typeof AdminWalletsTopupsRoute
  '/_admin/wallets/users': typeof AdminWalletsUsersRoute
  '/_admin/cards/': typeof AdminCardsIndexRoute
  '/_admin/kyc/': typeof AdminKycIndexRoute
  '/_admin/transactions/': typeof AdminTransactionsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_admin/wallets/': typeof AdminWalletsIndexRoute
  '/_admin/users/$id/cards': typeof AdminUsersIdCardsRoute
  '/_admin/users/$id/devices': typeof AdminUsersIdDevicesRoute
  '/_admin/users/$id/esims': typeof AdminUsersIdEsimsRoute
  '/_admin/users/$id/kyc': typeof AdminUsersIdKycRoute
  '/_admin/users/$id/notes': typeof AdminUsersIdNotesRoute
  '/_admin/users/$id/numbers': typeof AdminUsersIdNumbersRoute
  '/_admin/users/$id/transactions': typeof AdminUsersIdTransactionsRoute
  '/_admin/users/$id/wallets': typeof AdminUsersIdWalletsRoute
  '/_admin/users/$id/': typeof AdminUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cards'
    | '/dashboard'
    | '/wallets'
    | '/cards/$id'
    | '/cards/issued'
    | '/cards/programs'
    | '/kyc/$id'
    | '/transactions/$id'
    | '/users/$id'
    | '/wallets/fx'
    | '/wallets/payouts'
    | '/wallets/topups'
    | '/wallets/users'
    | '/cards/'
    | '/kyc/'
    | '/transactions/'
    | '/users/'
    | '/wallets/'
    | '/users/$id/cards'
    | '/users/$id/devices'
    | '/users/$id/esims'
    | '/users/$id/kyc'
    | '/users/$id/notes'
    | '/users/$id/numbers'
    | '/users/$id/transactions'
    | '/users/$id/wallets'
    | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/cards/$id'
    | '/cards/issued'
    | '/cards/programs'
    | '/kyc/$id'
    | '/transactions/$id'
    | '/wallets/fx'
    | '/wallets/payouts'
    | '/wallets/topups'
    | '/wallets/users'
    | '/cards'
    | '/kyc'
    | '/transactions'
    | '/users'
    | '/wallets'
    | '/users/$id/cards'
    | '/users/$id/devices'
    | '/users/$id/esims'
    | '/users/$id/kyc'
    | '/users/$id/notes'
    | '/users/$id/numbers'
    | '/users/$id/transactions'
    | '/users/$id/wallets'
    | '/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/cards'
    | '/_admin/dashboard'
    | '/_admin/wallets'
    | '/_admin/cards/$id'
    | '/_admin/cards/issued'
    | '/_admin/cards/programs'
    | '/_admin/kyc/$id'
    | '/_admin/transactions/$id'
    | '/_admin/users/$id'
    | '/_admin/wallets/fx'
    | '/_admin/wallets/payouts'
    | '/_admin/wallets/topups'
    | '/_admin/wallets/users'
    | '/_admin/cards/'
    | '/_admin/kyc/'
    | '/_admin/transactions/'
    | '/_admin/users/'
    | '/_admin/wallets/'
    | '/_admin/users/$id/cards'
    | '/_admin/users/$id/devices'
    | '/_admin/users/$id/esims'
    | '/_admin/users/$id/kyc'
    | '/_admin/users/$id/notes'
    | '/_admin/users/$id/numbers'
    | '/_admin/users/$id/transactions'
    | '/_admin/users/$id/wallets'
    | '/_admin/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/wallets': {
      id: '/_admin/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cards': {
      id: '/_admin/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/wallets/': {
      id: '/_admin/wallets/'
      path: '/'
      fullPath: '/wallets/'
      preLoaderRoute: typeof AdminWalletsIndexRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/transactions/': {
      id: '/_admin/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/kyc/': {
      id: '/_admin/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof AdminKycIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cards/': {
      id: '/_admin/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof AdminCardsIndexRouteImport
      parentRoute: typeof AdminCardsRoute
    }
    '/_admin/wallets/users': {
      id: '/_admin/wallets/users'
      path: '/users'
      fullPath: '/wallets/users'
      preLoaderRoute: typeof AdminWalletsUsersRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/_admin/wallets/topups': {
      id: '/_admin/wallets/topups'
      path: '/topups'
      fullPath: '/wallets/topups'
      preLoaderRoute: typeof AdminWalletsTopupsRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/_admin/wallets/payouts': {
      id: '/_admin/wallets/payouts'
      path: '/payouts'
      fullPath: '/wallets/payouts'
      preLoaderRoute: typeof AdminWalletsPayoutsRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/_admin/wallets/fx': {
      id: '/_admin/wallets/fx'
      path: '/fx'
      fullPath: '/wallets/fx'
      preLoaderRoute: typeof AdminWalletsFxRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/_admin/users/$id': {
      id: '/_admin/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/transactions/$id': {
      id: '/_admin/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AdminTransactionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/kyc/$id': {
      id: '/_admin/kyc/$id'
      path: '/kyc/$id'
      fullPath: '/kyc/$id'
      preLoaderRoute: typeof AdminKycIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cards/programs': {
      id: '/_admin/cards/programs'
      path: '/programs'
      fullPath: '/cards/programs'
      preLoaderRoute: typeof AdminCardsProgramsRouteImport
      parentRoute: typeof AdminCardsRoute
    }
    '/_admin/cards/issued': {
      id: '/_admin/cards/issued'
      path: '/issued'
      fullPath: '/cards/issued'
      preLoaderRoute: typeof AdminCardsIssuedRouteImport
      parentRoute: typeof AdminCardsRoute
    }
    '/_admin/cards/$id': {
      id: '/_admin/cards/$id'
      path: '/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof AdminCardsIdRouteImport
      parentRoute: typeof AdminCardsRoute
    }
    '/_admin/users/$id/': {
      id: '/_admin/users/$id/'
      path: '/'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof AdminUsersIdIndexRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/wallets': {
      id: '/_admin/users/$id/wallets'
      path: '/wallets'
      fullPath: '/users/$id/wallets'
      preLoaderRoute: typeof AdminUsersIdWalletsRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/transactions': {
      id: '/_admin/users/$id/transactions'
      path: '/transactions'
      fullPath: '/users/$id/transactions'
      preLoaderRoute: typeof AdminUsersIdTransactionsRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/numbers': {
      id: '/_admin/users/$id/numbers'
      path: '/numbers'
      fullPath: '/users/$id/numbers'
      preLoaderRoute: typeof AdminUsersIdNumbersRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/notes': {
      id: '/_admin/users/$id/notes'
      path: '/notes'
      fullPath: '/users/$id/notes'
      preLoaderRoute: typeof AdminUsersIdNotesRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/kyc': {
      id: '/_admin/users/$id/kyc'
      path: '/kyc'
      fullPath: '/users/$id/kyc'
      preLoaderRoute: typeof AdminUsersIdKycRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/esims': {
      id: '/_admin/users/$id/esims'
      path: '/esims'
      fullPath: '/users/$id/esims'
      preLoaderRoute: typeof AdminUsersIdEsimsRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/devices': {
      id: '/_admin/users/$id/devices'
      path: '/devices'
      fullPath: '/users/$id/devices'
      preLoaderRoute: typeof AdminUsersIdDevicesRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
    '/_admin/users/$id/cards': {
      id: '/_admin/users/$id/cards'
      path: '/cards'
      fullPath: '/users/$id/cards'
      preLoaderRoute: typeof AdminUsersIdCardsRouteImport
      parentRoute: typeof AdminUsersIdRoute
    }
  }
}

interface AdminCardsRouteChildren {
  AdminCardsIdRoute: typeof AdminCardsIdRoute
  AdminCardsIssuedRoute: typeof AdminCardsIssuedRoute
  AdminCardsProgramsRoute: typeof AdminCardsProgramsRoute
  AdminCardsIndexRoute: typeof AdminCardsIndexRoute
}

const AdminCardsRouteChildren: AdminCardsRouteChildren = {
  AdminCardsIdRoute: AdminCardsIdRoute,
  AdminCardsIssuedRoute: AdminCardsIssuedRoute,
  AdminCardsProgramsRoute: AdminCardsProgramsRoute,
  AdminCardsIndexRoute: AdminCardsIndexRoute,
}

const AdminCardsRouteWithChildren = AdminCardsRoute._addFileChildren(
  AdminCardsRouteChildren,
)

interface AdminWalletsRouteChildren {
  AdminWalletsFxRoute: typeof AdminWalletsFxRoute
  AdminWalletsPayoutsRoute: typeof AdminWalletsPayoutsRoute
  AdminWalletsTopupsRoute: typeof AdminWalletsTopupsRoute
  AdminWalletsUsersRoute: typeof AdminWalletsUsersRoute
  AdminWalletsIndexRoute: typeof AdminWalletsIndexRoute
}

const AdminWalletsRouteChildren: AdminWalletsRouteChildren = {
  AdminWalletsFxRoute: AdminWalletsFxRoute,
  AdminWalletsPayoutsRoute: AdminWalletsPayoutsRoute,
  AdminWalletsTopupsRoute: AdminWalletsTopupsRoute,
  AdminWalletsUsersRoute: AdminWalletsUsersRoute,
  AdminWalletsIndexRoute: AdminWalletsIndexRoute,
}

const AdminWalletsRouteWithChildren = AdminWalletsRoute._addFileChildren(
  AdminWalletsRouteChildren,
)

interface AdminUsersIdRouteChildren {
  AdminUsersIdCardsRoute: typeof AdminUsersIdCardsRoute
  AdminUsersIdDevicesRoute: typeof AdminUsersIdDevicesRoute
  AdminUsersIdEsimsRoute: typeof AdminUsersIdEsimsRoute
  AdminUsersIdKycRoute: typeof AdminUsersIdKycRoute
  AdminUsersIdNotesRoute: typeof AdminUsersIdNotesRoute
  AdminUsersIdNumbersRoute: typeof AdminUsersIdNumbersRoute
  AdminUsersIdTransactionsRoute: typeof AdminUsersIdTransactionsRoute
  AdminUsersIdWalletsRoute: typeof AdminUsersIdWalletsRoute
  AdminUsersIdIndexRoute: typeof AdminUsersIdIndexRoute
}

const AdminUsersIdRouteChildren: AdminUsersIdRouteChildren = {
  AdminUsersIdCardsRoute: AdminUsersIdCardsRoute,
  AdminUsersIdDevicesRoute: AdminUsersIdDevicesRoute,
  AdminUsersIdEsimsRoute: AdminUsersIdEsimsRoute,
  AdminUsersIdKycRoute: AdminUsersIdKycRoute,
  AdminUsersIdNotesRoute: AdminUsersIdNotesRoute,
  AdminUsersIdNumbersRoute: AdminUsersIdNumbersRoute,
  AdminUsersIdTransactionsRoute: AdminUsersIdTransactionsRoute,
  AdminUsersIdWalletsRoute: AdminUsersIdWalletsRoute,
  AdminUsersIdIndexRoute: AdminUsersIdIndexRoute,
}

const AdminUsersIdRouteWithChildren = AdminUsersIdRoute._addFileChildren(
  AdminUsersIdRouteChildren,
)

interface AdminRouteChildren {
  AdminCardsRoute: typeof AdminCardsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminWalletsRoute: typeof AdminWalletsRouteWithChildren
  AdminKycIdRoute: typeof AdminKycIdRoute
  AdminTransactionsIdRoute: typeof AdminTransactionsIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRouteWithChildren
  AdminKycIndexRoute: typeof AdminKycIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardsRoute: AdminCardsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminWalletsRoute: AdminWalletsRouteWithChildren,
  AdminKycIdRoute: AdminKycIdRoute,
  AdminTransactionsIdRoute: AdminTransactionsIdRoute,
  AdminUsersIdRoute: AdminUsersIdRouteWithChildren,
  AdminKycIndexRoute: AdminKycIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
